### ISSUE TITLE
Basic configuration

### ISSUE THREAD

**Issue by leoc** [michaelbeaumont/awesome-leader#2]
Hey there! Thanks for putting this out, seems to be exactly what I was looking for!

I am struggling a bit setting this up. I cloned the repo to my awesome config directory. When I require "awesome-leader/init" it complains about not being able to find ~lua-minilog~ I had to copy it into the root of my awesome config directory. Then it seemed to work. (Maybe there is a better way to set things up...)

Then I tried:

```
local leader = require "awesome-leader/awesome-leader"
leader.add_key("ms", function(args)
                   print(table.concat(args.keys) .. "," .. args.count)
                   print("ab expected") end)
awful.key({ }, "XF86Launch8", leader.get_leader())
``` 

It seems like the legacy config mechanism is deprecated?

Would you be so kind and share your setup for me to have some examples? That would be awesome! Thanks again :)

**Comment by michaelbeaumont** [comment]
Hey, sure I'll try to help.

You'll definitely want to use `require "awesome-leader"` to load the library, not load specific files. I personally have the `awesome-leader` directory at the same level as my `rc.lua`.

I don't use the deprecated method anymore, so I can't guarantee that it works to be honest... (I should write some tests I suppose)

The `README` explains the simple case I think best. It doesn't directly support multicharacter bindings directly anymore, you'll have to add a `bind` under `bind` (like in the example with `"tt"`).

**Comment by michaelbeaumont** [comment]
BTW, I personally use the "tt" -> "new tab" binding from the `README`, it's just a stripped down version of my config.

**Comment by leoc** [comment]
Alright. I played a bit with the new way. How would you write multiple prefixes for the same prefix?

`oo` - first level for prefix `o`

`ova` - prefix `ov`

`ovb` - prefix `ov`

Wrapping multiple `pure_sequence` calls does not work. I haven't had enough time to look through the code yet. Much function wrapping going on there ... :)

**Comment by michaelbeaumont** [comment]
Yeah I admit the code is pretty opaque, it's probably way more complicated than it needs to be.

**Comment by michaelbeaumont** [comment]
Sorry if I misinterpreted what you want but in kind of pseudocode:
```
sequence({
  {"o", sequence({
    {"o", pure(function() whatever end)}
    {"v", pure_sequence({
      {"a", function() whatever end}
      {"b", function() whatever end}
    })}
  })
})
```

Note that I renamed the functions (in the newest commit) to make more sense as well

**Comment by leoc** [comment]
Very nice, thank you!

This is what I have come up with. Basically I use it only to quickly open applications or invoking various emacs commands.

```lua
local function wrapEmacs(command)
   return function()
      awful.spawn("emacsclient -c -F \"((name . \\\"emacs-capture\\\") (height . 40) (width . 120))\" -e \"" .. command:gsub("\"", "\\\"") .. "\"")
   end
end

local function wrapSpawn(command)
   return function()
      awful.spawn(command)
   end
end

local function wrapBrowse(url)
   return function()
      awful.spawn(
	 "xdg-open " .. url:gsub("\"", "\\\""),
	 true,
	 function()
	    -- TODO: That does not work yet. Maybe I need to offload
	    -- that into a rule or signal handler
	    awful.client.urgent.jumpto()
	 end
      )
   end
end

local function prompt()
   awful.screen.focused().mypromptbox:run()
end

local leader = require "awesome-leader/awesome-leader"
local rec_leader =
  leader.wrap(
    leader.repeat_count,
    leader.sequence({
	  {"a",
	   leader.pure_sequence({
		 {"r", awesome.restart, "Restart window manager"},
		 {"l", wrapSpawn("dm-tool lock"), "Lock window manager session"},
		 {"a", prompt, "Run shell command"},
	   }),
	   "Window Manager"
	  },
	  {"s",
	   leader.pure_sequence({
		 {"o", wrapEmacs("(helm-org-rifle)"), "Search org files via org-rifle"},
		 {"l", wrapEmacs("(helm-locate)"), "Search files via locate"},
		 {"m", wrapEmacs("(helm-mu)"), "Search mails via Helm"},
	   }),
	   "Search & Find"
	  },
	  {"c",
	   leader.pure_sequence({
		 {"n", wrapEmacs("(org-capture nil \"n\")"), "Capture note to journal file"},
		 {"t", wrapEmacs("(org-capture nil \"t\")"), "Capture a new task"},
		 {"f", wrapEmacs("(org-capture nil \"f\")"), "Capture a new fact for Anki"},
		 {"c", wrapEmacs("(org-capture nil \"c\")"), "Capture a clockable interruption"},
		 {"p", wrapEmacs("(org-capture nil \"p\")"), "Capture a new blog post"},
	   }),
	   "Org Capture"
	  },
	  {"o",
	   leader.sequence({
		 {"b", leader.pure(wrapSpawn("chromium")), "Chromium"},
		 {"w", leader.pure(wrapSpawn("whatsapp")), "WhatsApp"},
		 {"c", leader.pure(wrapSpawn("chromium")), "Calendar"},
		 {"t", leader.pure(wrapSpawn("telegram-desktop")), "Telegram Messenger"},
		 {"e", leader.pure(wrapSpawn("emacsclient -c")), "Emacs"},
		 {"f", leader.pure(wrapSpawn("nemo")), "File Manager"},
		 {"a", leader.pure(wrapEmacs("(org-agenda nil)")), "Org Agenda"},
		 {"m", leader.pure(wrapSpawn("spotify")), "Music via Spotify"},
		 {"s", leader.pure(wrapSpawn("signal-desktop")), "Signal Messenger"},
		 {"p", leader.pure(wrapSpawn("pavucontrol")), "Pulse Audio Control"},
		 {"l",
		  leader.pure_sequence({
			{"w", wrapSpawn("libreoffice --writer"), "Libreoffice Writer"},
			{"c", wrapSpawn("libreoffice --calc"), "Libreoffice Calc"},
		  }),
		  "Open Libreoffice ..."
		 },
		 {"o",
		  leader.pure_sequence({
			{"j", wrapEmacs("(leoc/find-todays-journal-file)"), "Open Todays Journal File"},
			{"o", wrapEmacs("(leoc/org-overview)"), "Open Task & Appointment Overview"},
		  }),
		  "Open Org File ..."
		 },
	   }),
	   "Open Application ..."
	  },
	  {"m",
	   leader.pure_sequence({
		 {"s", wrapSpawn("(helm-mu)"), "Search Mail via Helm"},
		 {"m", wrapSpawn("(mu4e-compose-new)"), "Compose New Mail"},
		 {"u", wrapSpawn("(leoc/mu4e-update-and-show-inbox)"), "Update Mail & Show Inbox"},
		 {"i", wrapEmacs("(leoc/mu4e-show-inbox)"), "Show Mail Inbox"},
	   }),
	   "E-Mail"
	  },
	  {"w",
	   leader.sequence({
		 {"f", leader.pure(wrapBrowse("https://blog.fefe.de")), "Fefe"},
		 {"p",
		  leader.pure_sequence({
			-- ...
		  }),
		  "Open Project Websites ..."
		 },
		 {"w",
		  leader.pure_sequence({
			-- ...
		  }),
		  "Open Work Websites ..."
		 },
	   }),
	   "Open URLs ..."
	  },
	  {"u", leader.pure(awful.client.urgent.jumpto), "Jump to urgent window"},
    })
  )

local root_leader = leader.leader(rec_leader)
```

Have you had issues with the hotkey widget not showing certain levels of sequences? Currently the root level keys are not displayed. Maybe I overlooked something?

Also I would love to know your use-cases and sequences. For inspiration so to speak. Specifically I am wondering what experience you had with movement and client management here :)

Have a nice weekend!

**Comment by michaelbeaumont** [comment]
Here's a gist with [my current `keys.lua`](https://gist.github.com/michaelbeaumont/5b5120fb0fbb05a490079feabdebf0d5). Some of it links to some lua modules I think I haven't published yet so ignore those.

I'm not sure why your root keys aren't displayed. Are you binding your key to `root_leader`? Perhaps update to a newer version of awesome? The `hotkeys_popup` is a little fragile between versions.

What exactly do you mean by movement? Client management I still do with modkey shortcuts but I've put a lot of tab manipulation into `awesome-leader`.

Thanks for using `awesome-leader`! (If you still are, I know this is a little late :grimacing: )

**Comment by leoc** [comment]
Somehow I forgot what the issue or solution to the missing root_leader was...

Still I am using `awesome-leader` and am very happy :smiley: 

Thanks! :)
